apiVersion: v2
name: matrix-meetings-widget
description: A meetings widget for the Element messenger
type: application
version: 0.1.0
appVersion: "0.0.0"
home: https://github.com/nordeck/matrix-meetings
